theme: jekyll-theme-cayman
title: [ekorre scripts]
description: [Here you will find some scripts developed for different tasks during the development process of programming under Linux in different programming languages.]
