#!/bin/bash

# Verifico que haya ingresado una expresion matematica
if [ "$#" -eq "0" ]; then
    printf "\n    \e[1mHaber papi usemos plastilina ingresar una expresion matematica: \e[0m\e[96m1+2\n\n"
else
    clear
    printf "\n    Respuesta:\n\n"

    c=$(($1))
    echo -e "        $1 = $c\n"
fi
